### ISSUE TITLE
DSE key error "SIMD_LANE"

### ISSUE THREAD

**Issue by Hecmay** [UCLA-VAST/FlexCNN#7]
```shell
Dynamic tiling level:  2
Parallelizing using 36 processes...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/work/sx233/conda/envs/flexcnn/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/work/sx233/conda/envs/flexcnn/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "dse_p.py", line 653, in param_sweep
    SIMD_LANE = params['SIMD_LANE']
KeyError: 'SIMD_LANE'
"""
```

I suppose the key should be "SIMD_FACTOR"?

**Comment by atefehsz** [comment]
That is true. This issue is fixed now. Sorry for the inconvenience.
